{% set name = "wagtailmath" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/wagtailmath-{{ version }}.tar.gz
  sha256: 723c26fd6749efcf9981d215b8ec34f67bfbdf902997db931aa26bb803537265

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - wheel
    - pip
  run:
    - python >=3.8
    - django >=3.0
    - wagtail >=2.0

test:
  imports:
    - wagtailmath
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/JamesRamm/wagtailmath
  summary: Wagtail StreamField block for rendering mathematical equations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
